# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "talk-images-enfer-terraform-state"
    encrypt                     = true
    endpoint                    = "https://s3.fr-par.scw.cloud"
    key                         = "production/terraform.tfstate"
    region                      = "fr-par"
    skip_credentials_validation = true
    skip_metadata_api_check     = true
    skip_region_validation      = true
    use_path_style              = false
  }
}
