# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "scaleway" {
  # Credentials and settings from environment variables:
  # - SCALEWAY_ACCESS_KEY
  # - SCALEWAY_SECRET_KEY
  # - SCALEWAY_ORGANIZATION_ID
  # - SCALEWAY_PROJECT_ID
  # Region is set via module inputs
}
