# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
provider "scaleway" {
  region          = var.region
  zone            = var.zone
  organization_id = var.organization_id
  project_id      = var.project_id

  # Credentials from environment variables:
  # SCALEWAY_ACCESS_KEY
  # SCALEWAY_SECRET_KEY
}
